# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello',
                'doc_host': 'https://doyu.github.io',
                'git_url': 'https://github.com/doyu/nbdev-hello',
                'lib_path': 'nbdev_hello'},
  'syms': {'nbdev_hello.core': {'nbdev_hello.core.foo': ('core.html#foo', 'nbdev_hello/core.py')}}}
