name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Test with nbdev
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -U nbdev
          echo "Doing editable install..."
          test -f setup.py && pip install -e ".[dev]"
          echo "Check we are starting with clean git checkout"
          find
          if [[ `git status -uno` ]]; then
            git diff
            echo "git status is not clean"
            #false
          fi
          echo "Trying to strip out notebooks"
          nbdev_clean
          echo "Check that strip out was unnecessary"
          git status # display the status to see which nbs need cleaning up
          if [[ `git status -uno` ]]; then
            git status -uno
            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
            #false
          fi
